services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - TOKEN
      - SUBDOMAINS
      - LOG_FILE
    volumes:
      - "${CONTAINER_DATA_PATH}/duckdns/config:/config"

  vpn:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - PEERS
      - PEERDNS
      - SERVERURL
      - SERVERPORT
      - INTERNAL_SUBNET
      - ALLOWEDIPS
      - INTERFACE
      - LOG_CONFS
    volumes:
      - "${CONTAINER_DATA_PATH}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "${SERVERPORT}:${SERVERPORT}/udp"
      - 5000:5000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  vpn-ui:  # TODO: fix configs now coming from UI
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    restart: unless-stopped
    environment:
      - WGUI_SESSION_SECRET
      - WGUI_USERNAME
      - WGUI_PASSWORD
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
      - WGUI_LOG_LEVEL=DEBUG
    depends_on:
      - vpn
    cap_add:
      - NET_ADMIN
    network_mode: service:vpn
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - "${CONTAINER_DATA_PATH}/wireguard-ui/db:/app/db"
      - "${CONTAINER_DATA_PATH}/wireguard/config:/config"
