services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: "bd-duckdns-${ENV}"
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - ENV
      - TOKEN
      - SUBDOMAINS
      - LOG_FILE
#    healthcheck:
#      test: "bash healtcheck.sh $SUBDOMAINS"
#      interval: 90s
#      timeout: 60s
#      retries: 5
    volumes:
      - "${CONTAINER_DATA_PATH}/${ENV}/duckdns/config:/config"

  vpn:
    image: ghcr.io/linuxserver/wireguard
    container_name: "bd-wireguard-${ENV}"
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - ENV
      - PEERS
      - PEERDNS
      - SERVERURL
      - SERVERPORT
      - INTERNAL_SUBNET
      - ALLOWEDIPS
      - INTERFACE
      - LOG_CONFS
    volumes:
      - "${CONTAINER_DATA_PATH}/${ENV}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "${SERVERPORT}:${SERVERPORT}/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1