services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: bd-duckdns
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - TOKEN
      - SUBDOMAINS
      - LOG_FILE
    volumes:
      - "${CONTAINER_DATA_PATH}/duckdns/config:/config"

  vpn:
    image: ghcr.io/linuxserver/wireguard
    container_name: bd-wireguard
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - PEERS
      - PEERDNS
      - SERVERURL
      - SERVERPORT
      - INTERNAL_SUBNET
      - ALLOWEDIPS
      - INTERFACE
      - LOG_CONFS
    volumes:
      - "${CONTAINER_DATA_PATH}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "${SERVERPORT}:${SERVERPORT}/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1