services:
  openvpn-as:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - stack.env
    volumes:
      - "${CONTAINER_DATA_PATH}/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "${SERVERPORT}:${SERVERPORT}/udp"
    restart: unless-stopped
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1