version: "3"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      # INTERFACE: eth0 #optional
    volumes:
      - /opt/vpn/config:/config
    ports:
      - 843:943
      - 8443:9443
      - 1194:1194/udp
    restart: unless-stopped