services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - gitea-net   
    dns:
      - 10.80.0.2

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=$POSTGRES_USER
      - DB_PASSWD=$POSTGRES_PASSWORD
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "3022:22"
    depends_on:
      - db
    networks:
      - gitea-net
    dns:
      - 10.80.0.2

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea:3000
      - WOODPECKER_GITEA_CLIENT
      - WOODPECKER_GITEA_SECRET
      - WOODPECKER_AGENT_SECRET
      - WOODPECKER_SERVER_ADDR=:8000
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
    volumes:
      - woodpecker:/var/lib/woodpecker
    ports:
      - "3080:8000"
    depends_on:
      - gitea
    networks:
      - gitea-net
    dns:
      - 10.80.0.2

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    environment:
      - WOODPECKER_SERVER=http://woodpecker-server:8000
      - WOODPECKER_AGENT_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - woodpecker-server
    networks:
      - gitea-net
    dns:
      - 10.80.0.2

volumes:
  db:
  gitea:
  woodpecker:

networks:
  gitea-net:
    driver: bridge
