services:
  duckdns:
    image: k8s.gcr.io/git-sync:v3.1.3
    volumes:
      - ${PWD}/tmp:/tmp  # TODO: fix permissions, right now requires chmod 777
    environment:
      GIT_SYNC_REPO: https://github.com/musaalp/design-patterns.git  # TODO: change to ssh path
      GIT_SYNC_BRANCH: master
      # GIT_SYNC_ROOT: /data
      GIT_SYNC_DEST: repo
      # GIT_SYNC_PERIOD: 20
      GIT_SYNC_ONE_TIME: true