volumes:
  chatgpt_config_files:

services:

  chatgpt-config-writer:
    build:
      context: ./chatgpt_config_writer
    volumes:
      - chatgpt_config_files:/config
    environment:
      - CHATGPT_AUTH_TOKEN
    dns:
      - 10.80.0.2

  chatgpt-telegram:
    depends_on:
      - chatgpt-config-writer
    image: ghcr.io/m1guelpf/chatgpt-telegram
    container_name: chatgpt-telegram
    volumes:
      # your ".config" local folder must include a "chatgpt.json" file
      - chatgpt_config_files:/root/.config:ro
    environment:
      - TELEGRAM_ID
      - TELEGRAM_TOKEN
    labels:
       - "com.centurylinklabs.watchtower.enable=false"
    dns:
      - 10.80.0.2
