volumes:
  config: {}

services:

  chatgpt-config-writer:
    build:
      context: ./chatgpt_config_writer
      dockerfile: ./chatgpt_config_writer/Dockerfile
    volumes:
      - config:/config
    environment:
      - CHATGPT_AUTH_TOKEN

  chatgpt-telegram:
    depends_on:
      - chatgpt-config-writer
    image: ghcr.io/m1guelpf/chatgpt-telegram
    container_name: chatgpt-telegram
    volumes:
      # your ".config" local folder must include a "chatgpt.json" file
      # - config/:/root/.config
      - config:/root/.config:ro
    environment:
      - TELEGRAM_ID
      - TELEGRAM_TOKEN
