volumes:
  data:
  syncthing_config:
  rclone_config:

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - syncthing_config:/config:rw
      - data:/data:rw
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    volumes:
      - data:/data:shared
    user: $(id -u):$(id -g)

