name: Trigger Webhooks Based on Directory Updates
run-name: ${{ github.actor }} deploying a service

on:
  push:
    paths:
      - 'tests/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Webhook
        run: |
          WEBHOOKS_JSON=${{ vars.PORTAINER_WEBHOOKS }}
          WEBHOOK_URL=$(echo $WEBHOOKS_JSON | jq -r ".${{ matrix.directory[0] }}")
          echo "Webhook URL: $WEBHOOK_URL"
          curl -X POST $WEBHOOK_URL
