name: Trigger Webhooks Based on Directory Updates
run-name: ${{ gitea.actor }} deploying a service

on:
  push:
    paths:
      - 'tests/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - tests

    steps:
      - name: Set Webhook URL
        id: set-webhook-url
        run: |
          WEBHOOKS_JSON=${{ secrets.PORTAINER_WEBHOOKS }}
          echo "$WEBHOOKS_JSON"
          WEBHOOK_URL=$(echo $WEBHOOKS_JSON | jq -r ".${{ matrix.directory }}")
          echo "$WEBHOOKS_URL"
          # echo "::set-output name=WEBHOOK_URL::$WEBHOOK_URL"

      - name: Trigger Webhook
        if: ${{ github.event.head_commit.message != '' }}
        run: |
          curl -X POST ${{ steps.set-webhook-url.outputs.WEBHOOK_URL }}
