name: Trigger Webhooks Based on Directory Updates
run-name: ${{ gitea.actor }} deploying a service

on:
  push:
    paths:
      - 'tests/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - tests

    steps:
      - name: Trigger Webhook
        run: |
          # curl -X POST $(echo "${{ secrets.PORTAINER_WEBHOOKS }}" | jq -r ".${{ matrix.directory }}")
          # echo "$(echo \"${{ secrets.PORTAINER_WEBHOOKS }}\" | jq -r \".${{ matrix.directory }}\")"
          echo "${{ secrets.PORTAINER_WEBHOOKS }}"
