services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    # All env vars here: https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#environment-variables
    environment:
      - TZ
      - WEBPASSWORD
      - CONTAINER_DATA_PATH
    # Volumes store your data between container upgrades
    volumes:
     - '${CONTAINER_DATA_PATH}/pihole:/etc/pihole'
     - '${CONTAINER_DATA_PATH}/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
