services:

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    environment:
      - TZ=Europe/Madrid
      - CONTAINER_DATA_PATH
    volumes:
      - '${CONTAINER_DATA_PATH}/unbound:/opt/unbound/etc/unbound/'
    ports:
      - 5300:53/tcp
      - 5300:53/udp

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    # All env vars here: https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#environment-variables
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD
      - CONTAINER_DATA_PATH
      - PIHOLE_DNS_=127.0.0.1#5300
      - WEB_PORT=5380
    volumes:
     - '${CONTAINER_DATA_PATH}/pihole:/etc/pihole'
     - '${CONTAINER_DATA_PATH}/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
