services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - '${CONTAINER_DATA_PATH}/speedtest/config:/config'
    environment:
      - TZ=
      - PGID=
      - PUID=
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    dns:
        - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3