version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      TZ: "${TZ}"
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/config:/config
    network_mode: host
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    build: .
    environment:
      TZ: "${TZ}"
      HA_URL: "http://homeassistant:8123"
      TOKEN: "$HA_TOKEN"
      DASH_URL: "http://appdaemon:5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/appdaemon/conf:/conf
    depends_on:
      - homeassistant
    network_mode: host
    restart: unless-stopped
