version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    ports:
      - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/config:/config
    networks:
      ha:
        ipv4_address: 10.80.0.101
    restart: always

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - HA_URL="http://homeassistant:8123"
      - HA_KEY="$HA_TOKEN"
      - DASH_URL="http://appdaemon:5050"
    ports:
      - 5050:5050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/home-assistant/appdaemon/config:/conf
    depends_on:
      - homeassistant
    networks:
      ha:
        ipv4_address: 10.80.0.102
    restart: always

networks:
  ha:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 10.80.0.0/24
          gateway: 10.80.0.1