services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${HA_PORT:-8123} || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${DOCKER_DATA_PATH}/${ENV}/${STACK_DATA_PATH}/${CONTAINER_DATA_PATH}/config:/config"
    networks:
      ha:
        ipv4_address: 10.80.0.101
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${DA_PORT:-5050} || date >> /conf/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${DOCKER_DATA_PATH}/${ENV}/${STACK_DATA_PATH}/${CONTAINER_DATA_PATH}/conf:/conf"
    depends_on:
      - homeassistant
    networks:
      ha:
        ipv4_address: 10.80.0.102
    restart: unless-stopped


networks:
  ha:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 10.80.0.0/24
          gateway: 10.80.0.1