version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      TZ: "${TZ}"
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/config:/config
    networks:
      ha:
        - ipv4_address: 10.80.0.100
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      TZ: "${TZ}"
      HA_URL: "http://homeassistant:8123"
      TOKEN: "$HA_TOKEN"
      DASH_URL: "http://appdaemon:5050"
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:5050 || date >> /conf/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/appdaemon/conf:/conf
    depends_on:
      - homeassistant
    networks:
      ha:
        - ipv4_address: 10.80.0.102
    restart: unless-stopped

networks:
  ha:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 10.80.0.0/24
          gateway: 10.80.0.1