services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      - ENV
      - DOCKER_DATA_PATH
      - TZ
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${HA_PORT:-8123} || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DATA_PATH/$ENV/home-assistant/home-assistant/config:/config
    networks:
      ha:
        ipv4_address: 10.80.0.200
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - ENV
      - DOCKER_DATA_PATH
      - TZ
      - HA_TOKEN
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:${DA_PORT:-5050} || date >> /conf/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DATA_PATH/$ENV/home-assistant/appdaemon/conf:/conf
    depends_on:
      - homeassistant
    networks:
      ha:
        ipv4_address: 10.80.0.201
    restart: unless-stopped


networks:
  ha:
    driver: host