services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - CONTAINER_DATA_PATH
      - DISABLE_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - '$CONTAINER_DATA_PATH/homarr/configs:/app/data/configs'
      - '$CONTAINER_DATA_PATH/homarr/icons:/app/public/icons'
      - '$CONTAINER_DATA_PATH/homarr/data:/data'
    ports:
      - 7575:7575
    dns:
      - 10.80.0.2
    # healthcheck:
    #   test: curl -sS http://127.0.0.1:7575 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3