networks:
  internal-proxy:
    external: true

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=home.lan
      - VIRTUAL_PORT=7575
      - TZ=Europe/Madrid
      - CONTAINER_DATA_PATH
      - DISABLE_ANALYTICS=true
      - DEFAULT_COLOR_SCHEME=dark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - '$CONTAINER_DATA_PATH/homarr/configs:/app/data/configs'
      - '$CONTAINER_DATA_PATH/homarr/icons:/app/public/icons'
      - '$CONTAINER_DATA_PATH/homarr/data:/data'
    ports:
      - 7575:7575
    networks:
      - internal-proxy
    dns:
      - 10.80.0.2
    # healthcheck:
    #   test: curl -sS http://127.0.0.1:7575 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3