---
volumes:
  config:
  cache:
  jellyseerr:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - '8096:8096'
    volumes:
      - config:/config
      - cache:/cache
      - /home/gerardo/Videos:/media:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
      # - JELLYFIN_PublishedServerUrl=http://${HOST}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      # - LOG_LEVEL=debug
      - TZ=Europe/Madrid
      # - PORT=5055 #optional
    ports:
      - '8097:5055'
    volumes:
      - jellyseerr:/app/config
    restart: unless-stopped