---
volumes:
  cache:
  jellyfin:
  jellyseerr:
  radarr:
  sonarr:
  bazarr:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - '8096:8096'
    volumes:
      - jellyfin:/config
      - cache:/cache
      - /data:/media:ro
    environment:
      - TZ=Europe/Madrid
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
      # - JELLYFIN_PublishedServerUrl=http://${HOST}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    dns:
      - 10.80.0.2
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      # - LOG_LEVEL=debug
      - TZ=Europe/Madrid
      # - PORT=5055 #optional
    ports:
      - '8097:5055'
    volumes:
      - jellyseerr:/app/config
    dns:
      - 10.80.0.2
    restart: unless-stopped

  sonarr:
    restart: unless-stopped
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8099:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - sonarr:/config
      - /data:/data
    dns:
      - 10.80.0.2

  radarr:
    restart: unless-stopped
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "8098:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - radarr:/config
      - /data:/data
    dns:
      - 10.80.0.2
    
  bazarr:
    restart: unless-stopped
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "8094:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - bazarr:/config
      - /data:/data
    dns:
      - 10.80.0.2