# TODO: change stack to point to master
volumes:
  downloads:
  calibre_config:
  calibre_web_config:
  readarr_config:
  telethon_config:

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - calibre_config:/config
      # - /data/books/library:/config/books
      - downloads:/config/downloads
      - /data:/data
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
    
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - calibre_web_config:/config
      - /data/books/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  readarr:
    restart: unless-stopped
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8082:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - readarr_config:/config
      - /data:/data
  
  telethon_downloader:
    image: jsavargas/telethon_downloader
    container_name: telethon-downloader
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
      - TG_AUTHORIZED_USER_ID
      - TG_API_ID
      - TG_API_HASH
      - TG_BOT_TOKEN
    volumes:
      - telethon_config:/config
      - downloads:/download
      # - /path/to/download/torrent/watch:/watch
