# TODO: change stack to point to master
volumes:
  downloads:
  calibre_config:
  calibre_web_config:
  readarr_config:

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - calibre_config:/config:rw
      - /data/books/library:/config/books:rw
      - downloads:/config/downloads:rw
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
    
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - calibre_web_config:/config
      - /data/books/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8082:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
    volumes:
      - readarr_config:/config
      - /data:/data