version: '3'
services:
  homeassistant:
    container_name: app-daemon
    image: "acockburn/appdaemon:latest"
    environment:
      - HA_URL=hellosomething
      - TOKEN=sometoken
      - DASH_URL=someurl
