volumes:
  calibre_config:
  cops_config:
  library:

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#      - PASSWORD= #optional
#      - CLI_ARGS= #optional
    volumes:
      - calibre_config:/config:rw
      - library:/config/books:rw
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped

  cops:
    depends_on:
      - calibre
    image: lscr.io/linuxserver/cops:latest
    container_name: cops
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - cops_config:/config:rw
      - library:/books:rw
    ports:
      - 80:80
    restart: unless-stopped