services:
  portainer:
    image: portainer/portainer-ee:2.19.5
    container_name: portainer
    restart: unless-stopped
    healthcheck:
      test: curl -m 90 -sLf http://localhost:9443 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gerardo/.container-data/portainer/data:/data
    ports:
      - 9443:9443
