services:
  homeassistant:
    image: portainer/portainer-ee:2.17.1
    container_name: portainer
    restart: always
    user: 1000:1000
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:9443 || date >> /data/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    volumes:
      - "/home/gerardo/.container-data/portainer/data:/data"
    ports:
      - 9443:9443
