services:
  homeassistant:
    container_name: portainer
    image: portainer/portainer-ee:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    ports:
      - 9443:9443
    restart: always
