networks:
  internal-proxy:
    external: true

services:
  it-tools:
    image: 'ghcr.io/corentinth/it-tools:latest'
    ports:
      - '17700:80'
    restart: unless-stopped
    container_name: it-tools
    environment:
      - VIRTUAL_HOST=tools.home.lan
      - VIRTUAL_PORT=80
    networks:
      - internal-proxy
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  stirling-pdf:
    restart: unless-stopped
    image: frooodle/s-pdf:latest
    ports:
      - '17701:8080'
    volumes:
      - stirling-pdf-training:/usr/share/tessdata #Required for extra OCR languages
      - stirling-pdf-extra:/configs
      - stirling-pdf-custom:/customFiles/
    environment:
      - VIRTUAL_HOST=pdf.home.lan
      - VIRTUAL_PORT=8080
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
    networks:
      - internal-proxy
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  stirling-pdf-training:
  stirling-pdf-extra:
  stirling-pdf-custom: