services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "7080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - "${CONTAINER_DATA_PATH}/qbittorrent/config:/config"
      - "${CONTAINER_DATA_PATH}/qbittorrent/data:/data"  # TODO: requires change of ownership to UID:GID

  qbitmanage:
    container_name: qbitmanage
    image: ghcr.io/hotio/qbitmanage
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
      - ARGS
    volumes:
      - "${CONTAINER_DATA_PATH}/qbitmanage/config:/config"
      - "${CONTAINER_DATA_PATH}/qbittorrent/data:/data"