name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:ha appropriate/curl -s --retry 10 --retry-connrefused https://localhost:8123/api
