name: Deploy Portainer Stack

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Portainer Stack
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
